Absolutize config paths at config-read time, not at use time.
This also made it easier for me to realize that I needed to treat
`datadir` the same way I was treating `passwordFile`.

Auditors: benkraft

Test plan:
I temporarily uncommented "option 2" in config.json, then ran
   ./visualize_jenkins_perf_data.py -c jenkins_perf_visualizer/config.json deploy/build-webapp:9847
and it failed, as expected, with:
   IOError: [Errno 2] No such file or directory: u'/home/csilvers/khan/jenkins-perf-visualizer/jenkins_perf_visualizer/jenkins_api.token'