Add a username/password-file option for jenkins auth.
We'll be using this on toby, since keeper isn't installed there.

Auditors: benkraft

Test plan:
I temporarily uncommented out "option 2" of config.json and ran
   ./visualize_jenkins_perf_data.py -c jenkins_perf_visualizer/config.json deploy/build-webapp:9847
and it failed, as expected, with
   IOError: [Errno 2] No such file or directory: u'/home/csilvers/khan/jenkins-perf-visualizer/jenkins_perf_visualizer/jenkins_api.token'